### ISSUE TITLE
Are the 8.3.x releases supported?

### ISSUE THREAD

**Issue by durack1** [conda-forge/esmpy-feedstock#56]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems the latest [ESMF/ESMPy release is 8.3.1 (released 21 Sept 2022)](http://earthsystemmodeling.org/esmpy_doc/release/ESMF_8_3_1/html/), but the latest version available on [conda-forge is 8.2.0 (released 28 Oct 2021)](https://anaconda.org/conda-forge/esmpy/files). Should we expect support for the more recent releases ASAP? Is something holding it up?

### Installed packages

```shell
Nil
```

### Environment info

```shell
Nil
```

**Comment by xylar** [comment]
No yet, we are working on that over at https://github.com/conda-forge/esmf-feedstock/pull/78 and https://github.com/conda-forge/esmf-feedstock/pull/79.  There are missing dependencies including parallelio, which I have attempted to add here:
https://github.com/conda-forge/staged-recipes/pull/20231.  The review of that PR complained about static libraries being included in `libnetcdf` and `netcdf-fortran`.  I am attempting to get `libnetcdf` fixed in https://github.com/conda-forge/libnetcdf-feedstock/pull/140.  However, that PR is full of patches and it seems like we might wait for a release of 4.9.1 in a week or 2.

After `libnetcdf` goes in, I will attempt to follow up on the `netcdf-fortran` side.  Then, I will request a re-review of https://github.com/conda-forge/staged-recipes/pull/20231.  Once `parallelio` is available, I will attempt https://github.com/conda-forge/esmf-feedstock/pull/79 (and maybe https://github.com/conda-forge/esmf-feedstock/pull/78) again.

**Comment by durack1** [comment]
@xylar wow, ok you have this covered. I'll wait for the cogs to turn across the multiple repos and magic to land ~soon.

It appears that `osx-arm64` support is still a while off for ESMPy anyway if https://github.com/esmf-org/esmf/issues/60 is anything to go by, so aspirationally ESMF 8.4.0 might be a target for platform support

**Comment by xylar** [comment]
Yes, that was my impression, too.

**Comment by xylar** [comment]
Some headway has been made:
* We dropped static libraries in netcdf-fortran: https://github.com/conda-forge/netcdf-fortran-feedstock/pull/74
* We are about to do so in libnetcdf: https://github.com/conda-forge/libnetcdf-feedstock/pull/140

**Comment by billsacks** [comment]
> It appears that `osx-arm64` support is still a while off for ESMPy anyway if [esmf-org/esmf#60](https://github.com/esmf-org/esmf/issues/60) is anything to go by, so aspirationally ESMF 8.4.0 might be a target for platform support

With the changes in https://github.com/esmf-org/esmf/pull/79 ESMF now builds and runs nearly all tests cleanly on osx-arm64 with gfortran + clang. We plan to merge this PR within the next few days and then get it into the upcoming ESMF 8.4.0 release.

**Comment by durack1** [comment]
@billsacks this is great news!! I'll watch for 8.4.0 to land

**Comment by xylar** [comment]
Addressed in #58
